export { default as SplashScreen } from './SplashScreen'
export { default as Home } from './Home'
export { default as Favourites } from './Favourites'
export { default as AddItem } from './AddItem'
export { default as Login } from './Login'
export { default as Register } from './Register'
export { default as Profile } from './Profile'
export { default as Settings } from './Settings'
